name: "Local Remote Testing"

on:
  push:
    paths:
      - "main.py"
      - "setup.py"
      - ".github/workflows/ci.yml"
      - "requirements.txt"
      - "requirements_dev.txt"
  pull_request:
    paths:
      - "main.py"
      - "setup.py"
      - ".github/workflows/ci.yml"
      - "requirements.txt"
      - "requirements_dev.txt"


jobs:
  test-remote:
    name: "Tests"
    runs-on: ubuntu-22.04
    env:
        CONAN_LOGGING_LEVEL: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - run: |
        cd bincrafter_conan_remote/
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
    - name: Start Local Server
      run: |
        fastapi dev main.py & disown
    - name: Configure Conan
      run: |
        conan --version
        conan user
        conan config set general.revisions_enabled=1
        conan remote remove conancenter
        conan remote add inexorgame http://127.0.0.1:8000/r/github+bincrafters_remote+testing_v-998+inexorgame/
        conan remote list
    - name: Tests
      run: |
        conan download --recipe sdl2/2.0.14@bincrafters/stable
        conan download --recipe grpc/1.34.1@inexorgame/stable#0
