name: "Local Remote Testing"

on:
  push:
    paths:
      - ".github/workflows/ci.yml"
      - "bincrafters_conan_remote/main.py"
      - "bincrafters_conan_remote/remote.py"
      - "bincrafters_conan_remote/requirements.txt"
      - "bincrafters_conan_remote/requirements_dev.txt"
      - "setup.py"
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "bincrafters_conan_remote/main.py"
      - "bincrafters_conan_remote/remote.py"
      - "bincrafters_conan_remote/requirements.txt"
      - "bincrafters_conan_remote/requirements_dev.txt"
      - "setup.py"


jobs:
  test-remote:
    name: "Tests"
    runs-on: ubuntu-22.04
    env:
      CONAN_LOGGING_LEVEL: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install package
      run: |
        pip install .
    - name: Start Local Server
      run: |
        bincrafters-remote-conan run & disown
    - name: Configure Conan
      run: |
        conan --version
        conan user
        conan config set general.revisions_enabled=1
        conan remote remove conancenter
        conan remote add inexorgame "http://127.0.0.1:8000/r/github+bincrafters_remote+testing_v-998+inexorgame/"
        conan remote list
    - name: Tests
      run: |
        conan download --recipe sdl2/2.0.14@bincrafters/stable
        conan download --recipe grpc/1.34.1@inexorgame/stable#0
