name: "Generate Static Remote"

on:
  push:
    paths:
      - ".github/workflows/generate.yml"
      - "remote_repo_meta_files/**"
      - "bincrafters_conan_remote/generate.py"
      - "bincrafters_conan_remote/requirements.txt"
      - "bincrafters_conan_remote/requirements_dev.txt"
  pull_request:
    paths:
      - ".github/workflows/generate.yml"
      - "remote_repo_meta_files/**"
      - "bincrafters_conan_remote/generate.py"
      - "bincrafters_conan_remote/requirements.txt"
      - "bincrafters_conan_remote/requirements_dev.txt"

jobs:
  test-remote:
    name: "Generate"
    runs-on: ubuntu-22.04
    env:
        CONAN_LOGGING_LEVEL: 20
        REMOTE_NAME: inexorgame
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: "bincrafters/remote"
        ref: "testing/v-998"
        path: "remote"
        token: ${{ secrets.BOT_GITHUB_TOKEN }}
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install package
      run: |
        pip install .
    - name: Configure Conan
      run: |
        conan --version
        conan user
        conan config set general.revisions_enabled=1
        conan remote remove conancenter
    - name: Generate
      run: |
        bincrafters-conan-remote generate --remote-url https://bincrafters.jfrog.io/artifactory/api/conan/conan-legacy-inexorgame/ --remote-name ${{ env.REMOTE_NAME }}
    - name: List Generate Files
      run: |
        du -sh cache/
        ls -laR cache/
    - name: Commit Generate Files
      run: |
        git config --global user.email "${{ secrets.BOT_GITHUB_EMAIL }}"
        git config --global user.name "${{ secrets.BOT_GITHUB_NAME }}"
        rm -rf remote/r/${{ env.REMOTE_NAME }}/
        cp -r cache/generate/* remote/
        cp -r bincrafters_conan_remote/remote_repo_meta_files/* remote/
        cd remote
        git add -A .
        git commit -m "Update remote"
        git push
