name: "Generate Static Remote"

on:
  push:
    paths:
      - "generate.py"
      - ".github/workflows/generate.yml"
      - "remote_repo_meta_files/**"
  pull_request:
    paths:
      - "generate.py"
      - ".github/workflows/generate.yml"
      - "remote_repo_meta_files/**"

jobs:
  test-remote:
    name: "Generate"
    runs-on: ubuntu-22.04
    env:
        CONAN_LOGGING_LEVEL: 20
        REMOTE_NAME: inexorgame
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - run: |
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
    - name: Configure Conan
      run: |
        conan --version
        conan user
        conan config set general.revisions_enabled=1
        conan remote remove conancenter
    - name: Generate
      run: |
        python generate.py --remote-url https://bincrafters.jfrog.io/artifactory/api/conan/conan-legacy-inexorgame/ --remote-name ${{ env.REMOTE_NAME }}
    - name: List Generate Files
      run: |
        du -sh cache/
        ls -laR cache/
    - uses: actions/checkout@v4
      with:
        repository: "bincrafters/remote"
        ref: "testing/v-999"
        path: "remote"
    - name: Commit Generate Files
      run: |
        git config --global user.email "${{ secrets.BOT_GITHUB_EMAIL }}"
        git config --global user.name "${{ secrets.BOT_GITHUB_NAME }}"
        git config --global http.https://github.com/.extraheader "AUTHORIZATION: bearer ${{ secrets.BOT_GITHUB_TOKEN }}"
        rm -rf remote/r/${{ env.REMOTE_NAME }}/
        cp -r cache/generate/* remote/
        cp -r remote_repo_meta_files/* remote/
        cd remote
        git add -A .s
        git commit -m "Update remote"
        git push
